### ISSUE TITLE
Doesn't handle safe mode or open_basedir

### ISSUE THREAD

**Issue by mapkyca** [indieweb/mention-client-php#15]
Basically, curl does some odd things in many hosted environments where basedir or safe mode are set - namely, CURLOPT_FOLLOWLOCATION is disabled... for some reason.

This causes problems on a number of hosts where this is enabled by default. 

@benwerd's solution was to implement this in code, but that's not pretty in a library context. ~~Perhaps having the ability to pass a send function to hand off to might be a way to go?~~ I can of course just subclass...

(Refs idno/idno#629)

**Comment by aaronpk** [comment]
I assume this has been an acceptable solution so far? Is there anything else to resolve in this issue or can I close it?

**Comment by benwerd** [comment]
All happy at this end!
