### ISSUE TITLE
Spec mismatch: X-Pingback vs rel

### ISSUE THREAD

**Issue by Perlkonig** [indieweb/mention-client-php#28]
The code currently checks the HTTP headers for `X-Pingback`, but [the spec](https://www.w3.org/TR/webmention/#sender-discovers-receiver-webmention-endpoint) says to look for a generic `Link` header with a `rel` of `webmention`.

**Comment by aaronpk** [comment]
This library supports sending both pingback and webmention. To support Pingback, the link is discovered in the `X-Pingback` header http://www.hixie.ch/specs/pingback/pingback#TOC2.1 and Webmention uses a `Link` header with the rel value like you found.

**Comment by Perlkonig** [comment]
Egg on my face. I should know better than to speak publicly while still sick. I just didn't dig deep enough. Sorry to waste your time.

**Comment by aaronpk** [comment]
no problem!
