### ISSUE TITLE
Please re-license or dual license to MIT

### ISSUE THREAD

**Issue by marclaporte** [indieweb/mention-client-php#30]
This is easier to do before there are many contributors.

IMO, the best would be if libs like this one eventually became bundled in FLOSS PHP apps and this is easier with the MIT license than the Apache license. I was part of a group that worked hard to change the Bootstrap license from Apache to MIT for easy inclusion in GPL/LGPL apps: https://github.com/twbs/bootstrap/issues/2054

In my case, it's to include in Tiki Wiki CMS Groupware, in the context of WikiSuite, for which IndieWeb is an inspiration.
https://tiki.org/ -> Tiki is the Free/Libre/Open Source Web Application with the most built-in features
https://tiki.org/License
http://wikisuite.org/ -> WikiSuite is the most comprehensive and integrated Free / Libre / Open Source software suite ever developed.
http://wikisuite.org/Component-criteria#IndieWeb

Thanks!

**Comment by aaronpk** [comment]
Thanks for circling back on this! I'm definitely in support of a permissive license that allows this to be used in more places. Since there a few other contributors, we have to have them sign off on the license change.

I'll tag everyone on this issue, so if you're tagged here, please comment below that you agree to change the license to MIT. Thanks!

* [x] @aaronpk
* [ ] @pfefferle
* [ ] @HongPong
* [ ] @kylewm 
* [ ] @mapkyca
* [ ] @singpolyma
* [ ] @benwerd
* [ ] @marcusjfloyd

**Comment by pfefferle** [comment]
I agree with that license!

**Comment by singpolyma** [comment]
The Apache license is GPL compatible, I'm not sure what OP's concern is.  Moving to MIT (or, better, ISC) makes the license easier to read, but also takes out a lot of clarity (especially around software patents).

If we want a permissive license, Apache is already that and I don't see why it would be changed.

If we want an easy-to-read license, ISC is even shorter.  But that doesn't seems like a great criteria since Apache is widely-used enough to be decently understood by the community.

:-1:

**Comment by aaronpk** [comment]
@singpolyma from what I understand, the Apache license is not compatible with GPLv2, only GPLv3.  See the discussion on the linked Bootstrap issue: https://github.com/twbs/bootstrap/issues/2054#issuecomment-9092084

Here's where they finally finished the license change: https://github.com/twbs/bootstrap/issues/2054#issuecomment-30894685

**Comment by singpolyma** [comment]
Oh yes, I see. GPLv2. If compatability there is a goal we could dual-license Apachev2 and GPLv2-or-later -- that way we keep the nice permissive + patent protection of Apache, while ensuring GPL compatability for those who need it.

**Comment by aaronpk** [comment]
@marclaporte would a dual Apache+GPLv3 or v2 work for you? I don't have a lot of experience with dual-licensed projects.

**Comment by kylewm** [comment]
Happy to release my changes under MIT or whatever license you choose

**Comment by HongPong** [comment]
I'm fine with MIT license, that aligns with the Drupal community license standards easily : " Examples of compatible licenses include BSD/MIT-style "permissive" licenses or the Lesser General Public License (LGPL). " https://www.drupal.org/about/licensing 
Thanks for asking!

**Comment by mapkyca** [comment]
I don't really have enough data to really say, but I don't really have an objection.  I've a long standing dislike of GPL3, but that's a personal preference.

I'll leave @benwerd to comment on whether this poses any issues for Known, but I've no objection.

**Comment by marclaporte** [comment]
@aaronpk "would a dual Apache+GPLv3 or v2 work for you?"

No because we can't bundle in Tiki which is LGPL: https://tiki.org/License

LGPL 2.1 would work for Tiki, but there are CMSs that are MIT-licensed and we want them to join the party ;-)   With a quick search, I found: 
* https://pagekit.com/about
* https://bolt.cm/
* https://en.wikipedia.org/wiki/Refinery_CMS
* https://umbraco.com/products-and-support/license/
* And likely more candidates (not just CMSs) from https://en.wikipedia.org/wiki/Category:Software_using_the_MIT_license
* etc.

WikiSuite aggregates several software components: http://wikisuite.org/Software-Components
The criteria to be eligible is to be released "under an OSI-approved license": http://wikisuite.org/License

Current priority is to get it really easy to install. Next is to get tight interoperability between the components. And I'd like to use IndieWeb code / standards / approaches as much as possible so it works not just between WikiSuite components.

I see IndieWeb as technology building blocks, and as such, it should ideally be licensed in such a way that it can work with software "under an OSI-approved license". I think the IndieWeb community should determine such a principle and suggest a default license, for all current and future projects.

I realize that some are even Public Domain:
https://github.com/indieweb/php-mf2/blob/master/LICENSE.md

Best regards,

**Comment by aaronpk** [comment]
@marclaporte Thanks for the additional info. I agree it would be great to use as permissive a license as possible. I understand the concerns about the MIT license not having the patent clause, and I am wondering if you have a recommendation for how to resolve that while also being compatible with GPL/LGPL/MIT projects.

**Comment by singpolyma** [comment]
@marclaporte MIT licensed ones should be able to depend on Apache-licensed dependencies without issue.

Of course dual-license Apachev2 + LGPLv2.1-or-later is more general that my earlier suggestion. Good call.

**Comment by marclaporte** [comment]
@aaronpk: I don't know.

@singpolyma: If libs are dual-licensed, users can pick the one they want. What happens if they pick one without patent clause?

**Comment by singpolyma** [comment]
@marclaporte if users pick the one with no patent clause, they will be without any promise not to be litigated against for patents in modifications, etc

**Comment by aaronpk** [comment]
@singpolyma so is a dual Apache + MIT license acceptable then? Those who want the patent protection can use the Apache license, and those who want to use the project in a GPL/LGPL project can use the MIT license.

**Comment by singpolyma** [comment]
@aaronpk if we for some reason prefer than to an apache/lgpl relicense I will go along with it :)

**Comment by marclaporte** [comment]
@benwerd
@marcusjfloyd

Are you OK as well?

**Comment by marcusjfloyd** [comment]
Hey everyone,

Sorry for the delay. I'm ok with changing the license to MIT.

**Comment by marclaporte** [comment]
@benwerd : ping

**Comment by benwerd** [comment]
Groovy with me! Sorry for the delay.
