### ISSUE TITLE
add config option to set http user agent

### ISSUE THREAD

**Issue by aaronpk** [indieweb/mention-client-php#32]

**Comment by Zegnat** [comment]
It might be a good idea to have a default UA defined. Some website/server configuration may block POST requests with missing UA strings, see [#dev chat log](https://chat.indieweb.org/dev/2017-10-26#t1509018461844000).

**Comment by sknebel** [comment]
From googling, the very popular WordPress plugin [WordFence](https://www.wordfence.com/) has an explicit option to "block IPs sending POST requests that have empty UA and referer". This is something that'll likely come up often.
