### ISSUE TITLE
xmlrpc_decode returns null on successful pingback response in sendPingback() method in php 5.5.11

### ISSUE THREAD

**Issue by marcusjfloyd** [indieweb/mention-client-php#9]
xmlrpc_decode returns null in php 5.5.11 when the pingback response is a string which indicates a successful pingback response. I looked at the xlmrpc_decode method at php.net and realized that this method cannot be trusted: http://us1.php.net/manual/en/function.xmlrpc-decode.php

In the sendPingback() method we have:

    if(@$decoded=xmlrpc_decode($response)) {
      if(is_string($decoded))
        return true; // pingback returns a string like "Pingback was successful" when it works
      else
        return false; // otherwise returns an array like array('faultCode'=>48,'faultString'=>'The pingback has already been registered')
    } else {
      return false;
    }

Since $decoded is null on a successful pingback, the method will return false even though we got a successful response from the pingback target.

The following conditional block which replaces the block of code above solves the problem for everyone I believe:

    if(is_array(xmlrpc_decode($response))):
    	return false;
    elseif(is_string($response) && !empty($response)): 
    	return true;
    endif;

Pretty much it checks if xmlrpc_decode returns an array signifying we got an xml response which means you have an error, else if you get a non empty string then it's a success.

I hope this helped. Thanks for this library by the way. I'm in the middle of making my own blog for my website and this saved a lot of time.

**Comment by aaronpk** [comment]
Thanks for the fix! Not sure why this issue was left open! :+1:
